docker:
  - image: circleci/python:3.7.3
steps:
  - checkout
  - run: sudo chown -R circleci:circleci /usr/local/bin
  - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
  - restore_cache:  # このステップは依存関係をインストールする前に実行します
      key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
  - run:
      command: |
        pip install pipenv
        pipenv sync --dev
  - save_cache:
      key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      paths:
        - ".venv"
        - "/usr/local/bin"
        - "/usr/local/lib/python3.7/site-packages"