jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    parameters:
      python-version:
        type: string
    steps:
      - checkout
      - run: 
          name: set aws-cli
          command: |
            echo "test"
      - run:
          name: build docket image
          command: |
            echo "test2"
      - run:
          name: test3
          command: |
            echo "test3"
